### PR TITLE
Created a Tkinter Alarm clock

### PR DESCRIPTION
**Pull request by filza2112**

### CODE REVIEW

**Comment by TimTemi** [comment]
@filza2112  You did a great  job, but I do not have the write access, so I cant merge your PR, check for the owner of the repo.

**Comment by filza2112** [comment]
@TimTemi okay , no worries 
Thank you

**Comment by Shahrayar123** [comment]
Hi @filza2112,

Kindly add brief description of your project.

**Comment by filza2112** [comment]
@Shahrayar123 Done. Please check #76

**Pull request merged**
